name: Build and Publish

on:
  workflow_dispatch:
  repository_dispatch:
    types: [start-build]

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access

env:
  REGISTRY_PROJECT: public
  CHART_NAME: telegraf-snmp-mibs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - id: vars
      name: Env to vars
      run: |
        echo ::set-output name=REGISTRY_PROJECT::$REGISTRY_PROJECT
        echo ::set-output name=REGISTRY::harbor.local.winters.nz/$REGISTRY_PROJECT/$CHART_NAME


    - name: Bump version and push tag
      id: version
      uses: hennejg/github-tag-action@v4.3.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Login to Harbor
      uses: docker/login-action@v2
      with:
        registry: harbor.local.winters.nz
        username: robot$github
        password: ${{ secrets.HARBOR }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{steps.vars.outputs.REGISTRY}}:latest
          ${{steps.vars.outputs.REGISTRY}}:${{steps.version.outputs.new_version}}
